### ISSUE TITLE
"TypeError: Cannot read property 'wakeUp' of undefined"

### ISSUE THREAD

**Issue by wzhsh90** [OpenIMSDK/Open-IM-Uniapp-Demo#21]
运行后所有im 方法都找不到

**Comment by wzhsh90** [comment]
TypeError: Cannot read properties of undefined (reading 'wakeUp')
    at Vue.onShow (App.vue:10:1)
    at invokeWithErrorHandling (chunk-vendors.js:3400:26)
    at push.4UNb.Vue.__call_hook (chunk-vendors.js:10148:17)
    at o (chunk-vendors.js:14357:375874)
    at Vue.mounted (chunk-vendors.js:14357:384316)
    at invokeWithErrorHandling (chunk-vendors.js:3400:57)
    at callHook (chunk-vendors.js:5806:7)
    at mountComponent (chunk-vendors.js:5670:5)
    at push.4UNb.Vue.$mount (chunk-vendors.js:10164:10)
    at eval (main.js:19:5)

**Comment by Bloomingg** [comment]
请使用新版本，按照readme云打包自定义基座后运行
